# Render.com deployment configuration for Demiland Beauty Brand
# This file defines infrastructure as code for the project

services:
  # Production site (main branch)
  - type: static_site
    name: demiland-production
    env: node
    repo: https://github.com/KEYAJANI/demiland.git
    branch: main
    buildCommand: npm ci && npm run build:prod
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_ENVIRONMENT
        value: production
      - key: VITE_APP_NAME
        value: DEMILAND
      - key: VITE_APP_VERSION
        value: 1.0.0
      # Note: Sensitive env vars (SUPABASE_URL, SUPABASE_ANON_KEY) should be set via Render dashboard
    
    # Custom domain configuration (optional)
    # domains:
    #   - demiland.com
    #   - www.demiland.com
    
    # Headers for security and performance
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    
    # Redirects for SPA routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Staging site (dev branch)
  - type: static_site
    name: demiland-staging
    env: node
    repo: https://github.com/KEYAJANI/demiland.git
    branch: dev
    buildCommand: npm ci && npm run build:staging
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: staging
      - key: VITE_ENVIRONMENT
        value: staging
      - key: VITE_APP_NAME
        value: DEMILAND-DEV
      - key: VITE_APP_VERSION
        value: 1.0.0-dev
      - key: VITE_DEBUG_MODE
        value: true
    
    # Headers for staging
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    
    # Redirects for SPA routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html